"""fix_k1_execution_fees

Revision ID: 09529d9f8a5e
Revises: 98b9e0afc6bf
Create Date: 2026-09-29 22:02:24.745757
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09529d9f8a5e'
down_revision: str | None = '98b9e0afc6bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('execution_fee', sa.Numeric(precision=24, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'execution_fee')
    # ### end Alembic commands ###
