"""Phase F market data subsystem

Revision ID: 0df2a0ab4c3a
Revises: 50022f5ef28a
Create Date: 2026-09-17 21:14:13.286676
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0df2a0ab4c3a'
down_revision: str | None = '50022f5ef28a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle_identity')
    )
    op.create_index(op.f('ix_market_data_candles_symbol'), 'market_data_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_candles_timeframe'), 'market_data_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_candles_timestamp'), 'market_data_candles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_candles_timestamp'), table_name='market_data_candles')
    op.drop_index(op.f('ix_market_data_candles_timeframe'), table_name='market_data_candles')
    op.drop_index(op.f('ix_market_data_candles_symbol'), table_name='market_data_candles')
    op.drop_table('market_data_candles')
    # ### end Alembic commands ###
