"""add_backtest_runs_table

Revision ID: 50022f5ef28a
Revises: 53b197a7c64f
Create Date: 2026-09-16 22:04:45.262444
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '50022f5ef28a'
down_revision: str | None = '53b197a7c64f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('total_return_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('peak_equity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('minimum_equity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('average_win', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('average_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('trades_json', sa.JSON(), nullable=False),
    sa.Column('equity_curve_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_correlation_id'), 'backtest_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_idempotency_key'), 'backtest_runs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_backtest_runs_run_id'), 'backtest_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_run_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_idempotency_key'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_correlation_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
