"""phase_b_hardening

Revision ID: 53b197a7c64f
Revises: cd52aeed004f
Create Date: 2026-09-13 12:36:12.662208
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53b197a7c64f"
down_revision: Union[str, None] = "cd52aeed004f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_assessments", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_ai_assessments_correlation_id"), "ai_assessments", ["correlation_id"], unique=False
    )
    op.add_column("audit_events", sa.Column("risk_decision_id", sa.Uuid(), nullable=True))
    op.add_column("audit_events", sa.Column("order_intent_id", sa.Uuid(), nullable=True))
    op.add_column("fills", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_fills_correlation_id"), "fills", ["correlation_id"], unique=False)
    op.add_column("order_intents", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_order_intents_correlation_id"), "order_intents", ["correlation_id"], unique=False
    )
    op.add_column("orders", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.add_column("orders", sa.Column("symbol", sa.String(), nullable=False))
    op.add_column("orders", sa.Column("side", sa.String(), nullable=False))
    op.add_column("orders", sa.Column("order_type", sa.String(), nullable=False))
    op.add_column(
        "orders", sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False)
    )
    op.add_column("orders", sa.Column("rejection_reason", sa.String(), nullable=True))
    op.create_index(op.f("ix_orders_correlation_id"), "orders", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_orders_state"), "orders", ["state"], unique=False)
    op.create_index(op.f("ix_orders_symbol"), "orders", ["symbol"], unique=False)
    op.add_column("risk_decisions", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_risk_decisions_correlation_id"), "risk_decisions", ["correlation_id"], unique=False
    )
    op.add_column("signals", sa.Column("correlation_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_signals_correlation_id"), "signals", ["correlation_id"], unique=False)
    op.add_column("strategies", sa.Column("status", sa.String(), nullable=False))
    op.add_column("strategy_versions", sa.Column("status", sa.String(), nullable=False))
    op.add_column("strategy_versions", sa.Column("source_hash", sa.String(), nullable=True))
    op.create_unique_constraint(
        "uq_strategy_version", "strategy_versions", ["strategy_id", "version"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_strategy_version", "strategy_versions", type_="unique")
    op.drop_column("strategy_versions", "source_hash")
    op.drop_column("strategy_versions", "status")
    op.drop_column("strategies", "status")
    op.drop_index(op.f("ix_signals_correlation_id"), table_name="signals")
    op.drop_column("signals", "correlation_id")
    op.drop_index(op.f("ix_risk_decisions_correlation_id"), table_name="risk_decisions")
    op.drop_column("risk_decisions", "correlation_id")
    op.drop_index(op.f("ix_orders_symbol"), table_name="orders")
    op.drop_index(op.f("ix_orders_state"), table_name="orders")
    op.drop_index(op.f("ix_orders_correlation_id"), table_name="orders")
    op.drop_column("orders", "rejection_reason")
    op.drop_column("orders", "quantity")
    op.drop_column("orders", "order_type")
    op.drop_column("orders", "side")
    op.drop_column("orders", "symbol")
    op.drop_column("orders", "correlation_id")
    op.drop_index(op.f("ix_order_intents_correlation_id"), table_name="order_intents")
    op.drop_column("order_intents", "correlation_id")
    op.drop_index(op.f("ix_fills_correlation_id"), table_name="fills")
    op.drop_column("fills", "correlation_id")
    op.drop_column("audit_events", "order_intent_id")
    op.drop_column("audit_events", "risk_decision_id")
    op.drop_index(op.f("ix_ai_assessments_correlation_id"), table_name="ai_assessments")
    op.drop_column("ai_assessments", "correlation_id")
    # ### end Alembic commands ###
