"""Add expected_count to coverage

Revision ID: 7ce4195624be
Revises: d9850b179f64
Create Date: 2026-09-17 22:58:22.188674
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ce4195624be'
down_revision: str | None = 'd9850b179f64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_coverage', sa.Column('expected_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_coverage', 'expected_count')
    # ### end Alembic commands ###
