"""Add expected_count to coverage

Revision ID: 7ce4195624be
Revises: d9850b179f64
Create Date: 2026-09-17 22:58:22.188674
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce4195624be'
down_revision: Union[str, None] = 'd9850b179f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_coverage', sa.Column('expected_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_coverage', 'expected_count')
    # ### end Alembic commands ###
