"""Phase K1 paper trading

Revision ID: 98b9e0afc6bf
Revises: 34fb000a7c22
Create Date: 2026-09-29 19:15:43.867101
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98b9e0afc6bf"
down_revision: str | None = "34fb000a7c22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_sessions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("strategy_version", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("worker_owner_id", sa.Uuid(), nullable=True),
        sa.Column("worker_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_sessions_account_id"), "paper_sessions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_sessions_session_id"), "paper_sessions", ["session_id"], unique=True
    )
    op.create_index(
        op.f("ix_paper_sessions_strategy_id"), "paper_sessions", ["strategy_id"], unique=False
    )
    op.create_index(op.f("ix_paper_sessions_symbol"), "paper_sessions", ["symbol"], unique=False)
    op.create_table(
        "cash_reservations",
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("order_intent_id", sa.Uuid(), nullable=False),
        sa.Column("authorized_cash_requirement", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("creation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_intent_id"],
            ["order_intents.intent_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["paper_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_intent_id"),
    )
    op.create_index(
        op.f("ix_cash_reservations_reservation_id"),
        "cash_reservations",
        ["reservation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cash_reservations_session_id"), "cash_reservations", ["session_id"], unique=False
    )
    op.add_column(
        "orders", sa.Column("execution_price", sa.Numeric(precision=24, scale=8), nullable=True)
    )
    op.add_column(
        "risk_decisions",
        sa.Column("authorized_cash_requirement", sa.Numeric(precision=24, scale=8), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("risk_decisions", "authorized_cash_requirement")
    op.drop_column("orders", "execution_price")
    op.drop_index(op.f("ix_cash_reservations_session_id"), table_name="cash_reservations")
    op.drop_index(op.f("ix_cash_reservations_reservation_id"), table_name="cash_reservations")
    op.drop_table("cash_reservations")
    op.drop_index(op.f("ix_paper_sessions_symbol"), table_name="paper_sessions")
    op.drop_index(op.f("ix_paper_sessions_strategy_id"), table_name="paper_sessions")
    op.drop_index(op.f("ix_paper_sessions_session_id"), table_name="paper_sessions")
    op.drop_index(op.f("ix_paper_sessions_account_id"), table_name="paper_sessions")
    op.drop_table("paper_sessions")
    # ### end Alembic commands ###
