"""Add core trading domain models

Revision ID: cd52aeed004f
Revises:
Create Date: 2026-09-08 00:08:49.831967
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd52aeed004f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("component", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("trading_mode", sa.String(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_component"), "audit_events", ["component"], unique=False)
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_event_id"), "audit_events", ["event_id"], unique=True)
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_timestamp"), "audit_events", ["timestamp"], unique=False)
    op.create_index(
        op.f("ix_audit_events_trading_mode"), "audit_events", ["trading_mode"], unique=False
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cash", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("available_cash", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("equity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("total_realized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("total_unrealized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("total_exposure", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("reserved_capital", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_account_id"),
        "portfolio_snapshots",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_snapshot_id"),
        "portfolio_snapshots",
        ["snapshot_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_timestamp"), "portfolio_snapshots", ["timestamp"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("strategy_version", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("signal_type", sa.String(), nullable=False),
        sa.Column("proposed_entry_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("stop_loss", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("take_profit", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("rationale", sa.String(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_signal_id"), "signals", ["signal_id"], unique=True)
    op.create_index(op.f("ix_signals_strategy_id"), "signals", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_signals_symbol"), "signals", ["symbol"], unique=False)
    op.create_index(op.f("ix_signals_timestamp"), "signals", ["timestamp"], unique=False)
    op.create_table(
        "strategies",
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategies_strategy_id"), "strategies", ["strategy_id"], unique=True)
    op.create_table(
        "ai_assessments",
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("input_context_hash", sa.String(), nullable=False),
        sa.Column("recommendation", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_assessments_assessment_id"), "ai_assessments", ["assessment_id"], unique=True
    )
    op.create_index(
        op.f("ix_ai_assessments_signal_id"), "ai_assessments", ["signal_id"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("average_entry_price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=True),
        sa.Column("entry_signal_id", sa.Uuid(), nullable=True),
        sa.Column("stop_loss", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("take_profit", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_account_id"), "positions", ["account_id"], unique=False)
    op.create_index(op.f("ix_positions_position_id"), "positions", ["position_id"], unique=True)
    op.create_index(op.f("ix_positions_symbol"), "positions", ["symbol"], unique=False)
    op.create_table(
        "risk_decisions",
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rejection_code", sa.String(), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("calculated_risk", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("calculated_quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("risk_limit_applied", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.signal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_decisions_decision_id"), "risk_decisions", ["decision_id"], unique=True
    )
    op.create_index(
        op.f("ix_risk_decisions_signal_id"), "risk_decisions", ["signal_id"], unique=False
    )
    op.create_table(
        "strategy_versions",
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("supported_asset_classes", sa.JSON(), nullable=False),
        sa.Column("supported_timeframes", sa.JSON(), nullable=False),
        sa.Column("required_indicators", sa.JSON(), nullable=False),
        sa.Column("parameters_schema", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.strategy_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_versions_strategy_id"), "strategy_versions", ["strategy_id"], unique=False
    )
    op.create_table(
        "order_intents",
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("originating_signal_id", sa.Uuid(), nullable=False),
        sa.Column("risk_decision_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("order_type", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("stop_loss", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("take_profit", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("time_in_force", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("creation_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["originating_signal_id"],
            ["signals.signal_id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.decision_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_intents_account_id"), "order_intents", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_intents_idempotency_key"), "order_intents", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_order_intents_intent_id"), "order_intents", ["intent_id"], unique=True)
    op.create_index(op.f("ix_order_intents_symbol"), "order_intents", ["symbol"], unique=False)
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("intent_id", sa.Uuid(), nullable=False),
        sa.Column("broker_order_id", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["order_intents.intent_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("intent_id"),
    )
    op.create_index(op.f("ix_orders_broker_order_id"), "orders", ["broker_order_id"], unique=False)
    op.create_index(op.f("ix_orders_order_id"), "orders", ["order_id"], unique=True)
    op.create_table(
        "fills",
        sa.Column("fill_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("broker_fill_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("fee_asset", sa.String(), nullable=True),
        sa.Column("slippage", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fills_fill_id"), "fills", ["fill_id"], unique=True)
    op.create_index(op.f("ix_fills_order_id"), "fills", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fills_order_id"), table_name="fills")
    op.drop_index(op.f("ix_fills_fill_id"), table_name="fills")
    op.drop_table("fills")
    op.drop_index(op.f("ix_orders_order_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_broker_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_intents_symbol"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_intent_id"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_idempotency_key"), table_name="order_intents")
    op.drop_index(op.f("ix_order_intents_account_id"), table_name="order_intents")
    op.drop_table("order_intents")
    op.drop_index(op.f("ix_strategy_versions_strategy_id"), table_name="strategy_versions")
    op.drop_table("strategy_versions")
    op.drop_index(op.f("ix_risk_decisions_signal_id"), table_name="risk_decisions")
    op.drop_index(op.f("ix_risk_decisions_decision_id"), table_name="risk_decisions")
    op.drop_table("risk_decisions")
    op.drop_index(op.f("ix_positions_symbol"), table_name="positions")
    op.drop_index(op.f("ix_positions_position_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_account_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_ai_assessments_signal_id"), table_name="ai_assessments")
    op.drop_index(op.f("ix_ai_assessments_assessment_id"), table_name="ai_assessments")
    op.drop_table("ai_assessments")
    op.drop_index(op.f("ix_strategies_strategy_id"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_signals_timestamp"), table_name="signals")
    op.drop_index(op.f("ix_signals_symbol"), table_name="signals")
    op.drop_index(op.f("ix_signals_strategy_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_signal_id"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_portfolio_snapshots_timestamp"), table_name="portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_snapshots_snapshot_id"), table_name="portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_snapshots_account_id"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_audit_events_trading_mode"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_timestamp"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_component"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
