"""Refactor coverage fingerprint

Revision ID: d57668702d42
Revises: 7ce4195624be
Create Date: 2026-09-17 23:06:05.446535
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd57668702d42'
down_revision: str | None = '7ce4195624be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_coverage', sa.Column('actual_count', sa.Integer(), nullable=False))
    op.add_column('market_data_coverage', sa.Column('timestamp_fingerprint', sa.String(), nullable=False))
    op.drop_column('market_data_coverage', 'expected_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_coverage', sa.Column('expected_count', sa.INTEGER(), nullable=False))
    op.drop_column('market_data_coverage', 'timestamp_fingerprint')
    op.drop_column('market_data_coverage', 'actual_count')
    # ### end Alembic commands ###
