"""Phase F market data coverage

Revision ID: d9850b179f64
Revises: 0df2a0ab4c3a
Create Date: 2026-09-17 21:24:52.462536
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9850b179f64'
down_revision: Union[str, None] = '0df2a0ab4c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_coverage_symbol'), 'market_data_coverage', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_coverage_timeframe'), 'market_data_coverage', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_coverage_timeframe'), table_name='market_data_coverage')
    op.drop_index(op.f('ix_market_data_coverage_symbol'), table_name='market_data_coverage')
    op.drop_table('market_data_coverage')
    # ### end Alembic commands ###
