"""Pydantic schema for trading signals.

A Signal represents what a strategy WANTS to happen.
It is a proposal, NOT an executable order.
Signals never contain broker-specific fields.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import OrderSide, SignalType


class Signal(BaseModel):
    """Canonical representation of a trading signal generated by a Strategy."""

    model_config = ConfigDict(from_attributes=True)

    signal_id: UUID = Field(..., description="Unique identifier for this signal")
    correlation_id: UUID = Field(..., description="Links this signal to all downstream decisions")

    strategy_id: str = Field(..., description="ID of the strategy that generated this")
    strategy_version: str = Field(..., description="Version of the strategy")

    symbol: str = Field(..., description="Instrument symbol")
    timestamp: datetime = Field(..., description="UTC time the signal was generated")
    timeframe: str = Field(..., description="Timeframe the strategy was operating on")

    side: OrderSide = Field(..., description="BUY or SELL")
    signal_type: SignalType = Field(..., description="ENTRY or EXIT")
    quantity: Decimal = Field(..., gt=0, description="Proposed quantity to trade")

    # Strategy's proposed parameters (subject to Risk Engine modification)
    proposed_entry_price: Decimal | None = Field(
        None, description="Proposed limit/stop price if not market"
    )
    stop_loss: Decimal | None = Field(None, description="Proposed hard stop loss price")
    take_profit: Decimal | None = Field(None, description="Proposed take profit price")

    confidence: float | None = Field(
        None,
        ge=0.0,
        le=1.0,
        description="Strategy's confidence score (0-1)",
    )
    rationale: str | None = Field(None, description="Human readable rationale for the signal")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Additional signal context")
