from datetime import datetime
from decimal import Decimal
from typing import Dict, Optional, Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import OrderSide, SignalType


class Signal(BaseModel):
    """
    Canonical representation of a trading signal generated by a Strategy.
    A Signal is a proposal, NOT an executable order.
    """
    model_config = ConfigDict(from_attributes=True)

    signal_id: UUID = Field(..., description="Unique identifier for this signal")
    strategy_id: str = Field(..., description="ID of the strategy that generated this")
    strategy_version: str = Field(..., description="Version of the strategy")
    
    symbol: str = Field(..., description="Instrument symbol")
    timestamp: datetime = Field(..., description="UTC time the signal was generated")
    timeframe: str = Field(..., description="Timeframe the strategy was operating on")
    
    side: OrderSide = Field(..., description="BUY or SELL")
    signal_type: SignalType = Field(..., description="ENTRY or EXIT")
    
    # Strategy's proposed parameters (subject to Risk Engine modification)
    proposed_entry_price: Optional[Decimal] = Field(None, description="Proposed limit/stop price if not market")
    stop_loss: Optional[Decimal] = Field(None, description="Proposed hard stop loss price")
    take_profit: Optional[Decimal] = Field(None, description="Proposed take profit price")
    
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Strategy's confidence score (0-1)")
    rationale: Optional[str] = Field(None, description="Human readable rationale for the signal")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional signal context")
